import  time

print(time.localtime(time.time()))
print(time.time())
print(time.sleep(1))
print(time.localtime())
print(time.strftime('%a, %d %b %Y %H:%M:%S +0000', time.localtime()))
print(time.thread_time())
print(time.asctime(time.localtime()))
print(time.altzone)
print(time.timezone)
print(time.ctime())
print(time.gmtime())
print(time.mktime(time.localtime()))
print(time.monotonic_ns())
print(time.monotonic())
print(time.perf_counter())
print(time.process_time())
print(time.process_time_ns())
print(time.time_ns())
# print(time.tzset())